In [1]:
#Jacob Morrissey HW11 11/15/21

## Problem 2

In [2]:
import numpy as np
x = np.linspace(1,100,40)
y = np.array([ 7.7, 15.82307692, 23.94615385, 32.06923077, 40.19230769, 48.31538462, 56.43846154, 64.56153846, 72.68461538, 80.80769231, 88.93076923, 97.05384615, 105.17692308, 113.3 , 121.42307692, 129.54615385, 137.66923077, 145.79230769, 153.91538462, 162.03846154, 170.16153846, 178.28461538, 186.40769231, 194.53076923, 202.65384615, 210.77692308, 218.9, 227.02307692, 235.14615385, 243.26923077, 251.39230769, 259.51538462, 267.63846154, 275.76153846, 283.88461538, 292.00769231, 300.13076923, 308.25384615, 316.37692308, 324.5])

In [3]:
n = 1000
a = np.linspace(0.1,10,n)
b = np.linspace(0.1,15,n)
difs = np.empty((n,n))

In [4]:
for i in range(n):
    for j in range(n):
        y_mod = a[i] * x + b[j]
        difs[i,j] = np.sum( abs(y_mod - y) / y )
a_min = np.where( difs == np.min(difs) )[0][0]
b_min = np.where( difs == np.min(difs) )[1][0]

In [5]:
print('Problem 2:')
print('The line of best fit is y = %.3f x + %.3f \na = %.3f \nb = %.3f'%(a[a_min], b[b_min], a[a_min], b[b_min]))

Problem 2:
The line of best fit is y = 3.202 x + 4.485 
a = 3.202 
b = 4.485


## Problem 3

In [6]:
def wind_chill(T,V):
    """Given the temperature (F) and wind speed (mph), returns the wind chill temperature."""
    WC = 35.74 + 0.6215 * T - 35.75 * (V  ** 0.16) + .4275 * T * (V ** 0.16)
    return WC

def parallax_to_distance(stars):
    """Input a dictionary of stars {star name : parallax (arcseconds) }, outputs a new dictionary {star name : distance (parsecs) }"""
    d_stars = {}
    for i in stars.keys():
        d_stars[i] = 1 / stars[i]
    return d_stars

def lists_to_dict(list1, list2):
    """Input a list of strings and a list of numbers, outputs a dictionary with the given strings as keys and the given numbers as values. """
    dict_out = {}
    if type(list1[0]) == str:
        for i in range(len(list1)):
            dict_out[ list1[i] ] = list2[i]
    else:
        for i in range(len(list2)):
            dict_out[ list2[i] ] = list1[i]
    return dict_out

def matrix_mult(m1,m2):
    """Given two matrices, returns their product."""
    import numpy as np
    # need these if/else lines because np.shape  returns (j,) if the array is 1 x j instead of (1,j)
    if len( np.shape(m1) ) == 1:
        m1_i = 1
        m1_j = np.shape(m1)[0]
    else:
        m1_i = np.shape(m1)[0]
        m1_j = np.shape(m1)[1]
    if len( np.shape(m2) ) == 1:
        m2_i = 1
        m2_j = np.shape(m2)[0]
    else:
        m2_i = np.shape(m2)[0]
        m2_j = np.shape(m2)[1]
    
    if m1_j == m2_i:
        prod = np.empty(( m1_i , m2_j ))
        for i in range( m1_i ):
            for j in range( m2_j ):
                # need this bit because a 1 x j array can't be sliced using [i,:]
                if len( np.shape(m1) ) == 1:
                    prod[i,j] = np.sum( m1 * m2[:,j] )
                else:
                    prod[i,j] = np.sum( m1[i,:] * m2[:,j] )
        return prod
    
    # if matrices can't be multiplied in the given order, checks the reverse order
    elif m1_i == m2_j:
        print('These matrices can only be multiplied in the reverse order.')
        prod = np.empty(( m2_i , m1_j ))
        for i in range( m2_i ):
            for j in range( m1_j ):
                if len( np.shape(m2) ) == 1:
                    prod[i,j] = np.sum( m2 * m1[:,j] )
                else:
                    prod[i,j] = np.sum( m2[i,:] * m1[:,j] )
        return prod
    else:
        print('These matrices cannot be multiplied.')
        return

In [7]:
T = 20
V = 55

stars = {'Betelgeuse':7.63,'Antares': 5.89,'Spica': 13.06,'Proxima Cen': 768}

List_1 = [ 1, 3, 5, 10, 12, 14] 
List_2 = ['watermelon', 'melon', 'apple','strawberries', 'cherries', 'oranges' ]
List_3 = [ 'cars', 'motorcycles', 'bikes', 'skateboards'] 
List_4 = [ 200, 150, 10, 67 ]

A1 = np.array( [ [1, 2, 3 ], [4, 5, 6] ]) 
A2 = np.array( [ [2, 3] , [2 , 2 ] ] ) 
B1 = np.array( [ [1, 0], [0, 1] ]) 
B2 = np.array( [ [4, 1], [ 2,1 ] ] )
C1 = np.array( [ [1, 0, 3], [0, 1, 4], [2, 1 , 8] ])
C2 = np.array( [4, 1, 5 ])

In [8]:
print('Problem 3:')
print('\na')
print('The current wind chill temperature is %.2f F.' %(wind_chill(T,V)))
print('\nb')
print(parallax_to_distance(stars))
print('\nc')
print(lists_to_dict(List_1, List_2),'\n')
print(lists_to_dict(List_3, List_4))
print('\nd')
print(matrix_mult(A1,A2),'\n')
print(matrix_mult(B1,B2),'\n')
print(matrix_mult(C1,C2))

Problem 3:

a
The current wind chill temperature is -3.47 F.

b
{'Betelgeuse': 0.1310615989515072, 'Antares': 0.16977928692699493, 'Spica': 0.07656967840735068, 'Proxima Cen': 0.0013020833333333333}

c
{'watermelon': 1, 'melon': 3, 'apple': 5, 'strawberries': 10, 'cherries': 12, 'oranges': 14} 

{'cars': 200, 'motorcycles': 150, 'bikes': 10, 'skateboards': 67}

d
These matrices can only be multiplied in the reverse order.
[[14. 19. 24.]
 [10. 14. 18.]] 

[[4. 1.]
 [2. 1.]] 

These matrices can only be multiplied in the reverse order.
[[14.  6. 56.]]
